Repository FESPfinal/EDUTUBE, pull requests merged in 2023-12, with the labels that each got.

#70 [Feat/66] 구매 목록 불러오기 기능 구현
  app/mypage/layout.tsx
  app/mypage/purchase/page.tsx
  src/components/views/mypage/purchase/PurchaseList.tsx
  src/queries/coffeechat/order/useSelectOrder.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#73 [Refactor/72] : 회원가입 링크 추가, 회원가입 시 nav 안보이게 하기
  app/login/layout.tsx
  app/sign-up/layout.tsx
  app/sign-up/profile/page.tsx
  src/components/block/navbar/Navbar.tsx
  src/components/views/login/Login.tsx
  src/components/views/sign-up/SignUp.tsx
Labels: 🔨 Refactor, 🎨 UI

#76 Fix: 메뉴바 수정
  src/components/views/mypage/MypageMenu.tsx
Labels: ✨ Feature

#94 [Feat/90]: 프로필 이미지 등록 및 불러오기 기능 추가
  next.config.js
  src/components/atom/ProfileImageUploader.tsx
  src/components/views/mypage/MypageSellerInfo.tsx
  src/components/views/mypage/MypageUserInfo.tsx
  src/components/views/sign-up/SignUpSellerInfo.tsx
  src/components/views/sign-up/SignUpUserInfo.tsx
  src/helper/constants/apiConst.ts
  src/helper/types/userInfoTypes.ts
  src/queries/common/useCreateFile.ts
  src/queries/signUp/useCreateUser.ts
Labels: ✨ Feature

#97 [Feat/95]: axios interceptor 구현 및 refresh Token 수정, userInfo zustand에 설정
  package-lock.json
  package.json
  src/components/block/navbar/NavLogoutModal.tsx
  src/components/views/login/Login.tsx
  src/components/views/mypage/MypageInfo.tsx
  src/components/views/mypage/MypageMenu.tsx
  src/components/views/sign-up/SignUp.tsx
  src/components/views/sign-up/SignUpIdPw.tsx
  src/components/views/sign-up/SignUpSellerInfo.tsx
  src/components/views/sign-up/SignUpUserInfo.tsx
  src/helper/types/userInfo.ts
  src/helper/utils/useEdutubeAxios.ts
  src/queries/auth/useRefreshToken.ts
  src/queries/login/useLogin.ts
  src/queries/mypage/useSelectUserInfo.ts
  src/stores/auth.ts
  src/stores/userInfo.ts
Labels: ✨ Feature, 📬 API

#101 [Feat/100]: user, seller 내정보 수정 기능 구현
  src/components/views/mypage/MypageSellerInfo.tsx
  src/components/views/mypage/MypageUserInfo.tsx
  src/components/views/sign-up/SignUpSellerInfo.tsx
  src/helper/utils/useEdutubeAxios.ts
  src/queries/mypage/useUpdateUserInfo.ts
  src/queries/signUp/useCheckDuplicateEmail.ts
  src/queries/signUp/useCreateUser.ts
Labels: ✨ Feature, 📬 API

#104 [Feat/102]: 로그인 여부, user-type에 따른 페이지 접근 권한 설정 / 404 페이지 구현
  app/not-found.tsx
  middleware.ts
  src/queries/login/useLogin.ts
Labels: ✨ Feature, 🎨 UI

#21 [UI/11]: CheckBox atom 구현
  src/components/atom/CheckBox.tsx
Labels: 🎨 UI

#22 [UI/20] GroupButtons 구현
  src/components/atom/GroupButtons.tsx
Labels: 🎨 UI

#114 [Feat/111] 상세페이지 extra data 보여주기 및 css 정리
  package-lock.json
  package.json
  src/components/atom/Avatar.tsx
  src/components/atom/Button.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
Labels: ✨ Feature, 🎨 UI

#117 [Feat/116] regist extra값 수정
  src/components/views/coffeechat/regist/CoffeechatRegist.tsx
  src/helper/types/tempProduct.ts
  src/queries/coffeechat/tempUseCreateProduct.ts
Labels: ✨ Feature, 📬 API

#119 [Hotfix/2] buyQuantity 속성 추가
  src/components/views/coffeechat/regist/CoffeechatRegist.tsx
  src/helper/types/tempProduct.ts
  src/queries/coffeechat/tempUseCreateProduct.ts
Labels: 🐞 BugFix

#120 [Feat/110]: 장바구니 UI 및 기능 구현
  app/mypage/cart/layout.tsx
  app/mypage/cart/page.tsx
  src/components/views/mypage/MypageMenu.tsx
  src/components/views/mypage/cart/Cart.tsx
  src/components/views/mypage/cart/CartItem.tsx
  src/helper/constants/commons.ts
  src/helper/types/order.ts
  src/queries/coffeechat/cart/useCreateCoffeechatCart.ts
  src/queries/coffeechat/cart/useDeleteCoffeechatCart.ts
  src/queries/coffeechat/order/useUpdateOrder.tsx
  src/queries/mypage/cart/useSelectCart.ts
  src/queries/signUp/useCreateUser.ts
  src/stores/userInfo.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#121 [Feat/109]: 구매목록 확인 리스트
  src/components/views/mypage/MypageSellerInfo.tsx
  src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/components/views/mypage/purchase/PurchaseList.tsx
  src/queries/coffeechat/order/useSelectOrder.ts
  src/queries/common/useCreateFile.ts
  src/queries/mypage/myCoffeechat/useSelectMyCoffeechat.tsx
Labels: ✨ Feature, 📬 API

#125 [Feat/83]: 내 커피챗 리스트, 상세 확인
  src/components/views/mypage/myCoffechat/MyCoffeechatDetail.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatItem.tsx
  src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
  src/helper/utils/datetime.ts
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/mypage/myCoffeechat/useSelectMyCoffeechat.tsx
  src/queries/mypage/myCoffeechat/useSelectSellerOrders.ts
Labels: ✨ Feature, 📬 API

#123 [Feat/118] 상세페이지 및 예약하기 모달 기능
  app/@modal/(.)coffeechat/info/[_id]/reserve/page.tsx
  app/@modal/default.tsx
  app/default.tsx
  app/layout.tsx
  src/components/atom/Button.tsx
  src/components/block/modal/Modal.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
Labels: ✨ Feature, 🎨 UI

#128 [Feat/126]: 상단 nav 장바구니 추가 및 로그인/로그아웃 반응속도 향상
  app/layout.tsx
  next.config.js
  public/images/placeholder-image.png
  src/components/block/navbar/NavLogin.tsx
  src/components/block/navbar/NavLogout.tsx
  src/components/block/navbar/NavLogoutModal.tsx
  src/components/block/navbar/Navbar.tsx
  src/components/views/login/Login.tsx
  src/components/views/mypage/cart/CartItem.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/queries/coffeechat/order/useSelectOrder.ts
  src/queries/login/useSelectCartMutate.ts
  src/stores/cart.ts
Labels: ✨ Feature, 🎨 UI

#129 [Feat/109]: 채팅시작 버튼 및 후기등록 버튼 구현 및 NextImage 아톰 컴포넌트 제작
  package-lock.json
  package.json
  src/components/atom/Button.tsx
  src/components/atom/NextImge.tsx
  src/components/atom/Skeleton.tsx
  src/components/views/mypage/cart/CartItem.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatItem.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/components/views/mypage/purchase/PurchaseList.tsx
Labels: ✨ Feature, 🎨 UI

#134 [Feat/124] 후기 등록하기 모달 구현
  app/@modal/(.)mypage/reserved/[_id]/review/page.tsx
  src/components/atom/Button.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/mypage/review/ReplyCreateModal.tsx
  src/helper/types/reply.ts
  src/queries/coffeechat/review/useCreateReply.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#132 [Fix/131]: build시 발생하는 에러 해결
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/components/views/coffeechat/regist/FirstRegist.tsx
  src/components/views/mypage/cart/Cart.tsx
  src/queries/coffeechat/useCreateProduct.ts
  src/queries/coffeechat/useSelectCoffeechatList.ts
  src/queries/signUp/useCreateUser.ts
Labels: 🐞 BugFix

#140 [Feat/133]: 내가 등록한 커피챗 내에서 제목 검색기능 구현
  src/components/block/searchBar/SearchBar.tsx
  src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
  src/queries/mypage/myCoffeechat/useSelectSellerItemSearch.tsx
Labels: ✨ Feature

#138 [Feat/135] 후기 상세 목록 기능
  src/components/atom/NextImage.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/review/ReplyItem.tsx
  src/components/views/mypage/cart/CartItem.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatItem.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/queries/coffeechat/review/useSelectReply.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#146 [Feat/144]: 후기 전체 요약 컴포넌트
  src/components/atom/RatingStarGroup.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/review/RatingSummary.tsx
Labels: ✨ Feature, 🎨 UI

#150 [Refac/149] 예약된 일정 보여주는 부분 로직 수정
  src/components/views/coffeechat/info/CoffeechatCartModal.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
Labels: ✨ Feature, 🔨 Refactor

#152 [Feat/151] : ssr, metadata, favicon 설정
  app/coffeechat/info/[_id]/page.tsx
  app/coffeechat/page.tsx
  app/favicon.ico
  app/layout.tsx
  app/page.tsx
  public/images/edutube.jpg
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/coffeechat/useSelectCoffeechatList.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#154 [Feat/139] update 기능 구현
  app/coffeechat/update/[_id]/page.tsx
  app/coffeechat/update/page.tsx
  src/components/atom/Category.tsx
  src/components/atom/ImageUploader.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/update/CoffeechatUpdate.tsx
  src/queries/coffeechat/update/useUpdateCoffeechat.tsx
Labels: 📬 API, 🎨 UI

#156 [Feat/155] 삭제하기 기능 구현
  app/coffeechat/page.tsx
  app/page.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/delete/useDeleteCoffeechat.tsx
Labels: ✨ Feature, 📬 API

#157 [Feat/145] : 채팅 기능 구현 및 마이페이지 스크롤 UI 수정
  app/@modal/(.)mypage/my-coffeechat/[_id]/chat/page.tsx
  app/mypage/chat/[_id]/page.tsx
  app/mypage/chat/page.tsx
  app/not-found.tsx
  package-lock.json
  package.json
  public/images/oops.png
  src/components/atom/ProfileImageUploader.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/components/views/coffeechat/regist/CoffeechatRegist.tsx
  src/components/views/login/Login.tsx
  src/components/views/mypage/MypageInfo.tsx
  src/components/views/mypage/MypageMenu.tsx
  src/components/views/mypage/MypageSellerInfo.tsx
  src/components/views/mypage/MypageUserInfo.tsx
  src/components/views/mypage/cart/Cart.tsx
  src/components/views/mypage/chat/ChatRoom.tsx
  src/components/views/mypage/chat/CreateRoom.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatCreateChatModal.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailChatButton.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatItem.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/components/views/mypage/purchase/PurchaseList.tsx
  src/helper/constants/apiConst.ts
  src/helper/constants/commons.ts
  src/helper/utils/datetime.ts
  src/helper/utils/useEdutubeAxios.ts
  src/helper/utils/websocket/index.ts
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/mypage/myCoffeechat/useSelectMyCoffeechatChatLink.tsx
  src/queries/mypage/myCoffeechat/useUpdateMyCoffeechatChatLink.tsx
  tailwind.config.js
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 🎨 UI

#159 [Feat/158] : 수정안되있던 axios edutubeAxios로 모두 변경 및 필요없는 cookie 제거
  src/components/block/navbar/NavLogoutModal.tsx
  src/components/views/login/Login.tsx
  src/helper/utils/useEdutubeAxios.ts
  src/queries/coffeechat/useCreateProduct.ts
  src/queries/coffeechat/useGetUserInfo.ts
  src/queries/member/useSelectMemberInfo.ts
  src/queries/member/useSelectMemberInfoExtra.ts
Labels: 🔨 Refactor

#162 [UI/161] 배너 업데이트
  public/images/banner.png
  src/components/views/coffeechat/CoffeechatLists.tsx
Labels: 🎨 UI

#167 Fix: 주문 시 address name 추가 및 내 커피챗 구매자 이름 표시
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
Labels: 🐞 BugFix

#172 [Fix/169] 채팅 버튼 활성화 및 렌더링 관련 이슈 수정
  .env.development.local
  .env.production.local
  app/default.tsx
  app/not-found.tsx
  src/components/atom/NextImage.tsx
  src/components/atom/SkeletonBox.tsx
  src/components/atom/SpinningPage.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetail.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailBody.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailChatButton.tsx
  src/components/views/mypage/myCoffechat/MyCoffeechatDetailHead.tsx
  src/components/views/mypage/myCoffechat/MypageMyCoffeechat.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/components/views/mypage/purchase/PurchaseList.tsx
  src/helper/utils/datetime.ts
  src/queries/mypage/myCoffeechat/useSelectMyCoffeechatChatLink.tsx
Labels: 🐞 BugFix

#179 [Feat/164]: 장바구니 수량 체크 변경 및 커피챗 목록에서 카드 정보(온라인, 오프라인, 카테고리, 장소) 추가
  src/components/block/navbar/NavLogoutModal.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatCartModal.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/components/views/login/Login.tsx
  src/components/views/mypage/cart/Cart.tsx
  src/components/views/mypage/cart/CartItem.tsx
  src/components/views/mypage/purchase/PurchaseCard.tsx
  src/helper/utils/datetime.ts
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/common/useCreateFile.ts
  src/queries/mypage/useUpdateUserInfo.ts
  src/stores/cart.ts
Labels: ✨ Feature, 🎨 UI

#173 [Docs/170]: README 수정
  README.md
Labels: 📃 Docs

#182 [Feat/180]: 커피챗 리스트에서 검색 기능 추가
  src/components/block/searchBar/SearchBar.tsx
  src/components/views/coffeechat/CoffeechatItem.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/queries/coffeechat/useSelectCoffeechatList.ts
  src/queries/coffeechat/useSelectCoffeechatSearch.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI

#184 [Feat/168]: Loading 및 Footer , 배너 이미지 수정
  app/layout.tsx
  app/loading.tsx
  app/page.tsx
  public/images/main-logo-book.png
  public/images/main-logo-book.svg
  src/components/atom/SkeletonBox.tsx
  src/components/block/navbar/Navbar.tsx
  src/components/block/searchBar/SearchBar.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatCartModal.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/components/views/coffeechat/info/CoffeechatModal.tsx
  src/components/views/coffeechat/regist/CoffeechatRegist.tsx
  src/components/views/coffeechat/update/CoffeechatUpdate.tsx
  src/components/views/footer/Footer.tsx
  src/components/views/loading/Loading.tsx
  src/components/views/loading/LoadingDefault.tsx
  src/components/views/loading/LoadingHome.tsx
  src/components/views/loading/LoadingRequest.tsx
  src/components/views/mypage/cart/Cart.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 UI
