Repository FESPfinal/EDUTUBE, pull requests merged in 2023-11, with the labels that each got.

#5 [UI/3] tailwind config 설정 및 Theme 적용
  README.md
  app/coffeechat/info/[_id]/page.tsx
  app/coffeechat/layout.tsx
  app/coffeechat/page.tsx
  app/coffeechat/regist/page.tsx
  app/coffeechat/update/page.tsx
  app/create/page.tsx
  app/globals.css
  app/layout.tsx
  app/login/layout.tsx
  app/login/page.tsx
  app/mypage/cart/page.tsx
  app/mypage/layout.tsx
  app/mypage/likes/page.tsx
  app/mypage/my-coffeechat/page.tsx
  app/mypage/my-video/page.tsx
  app/mypage/page.tsx
  app/mypage/reserved/page.tsx
  app/mypage/user/page.tsx
  app/page.tsx
  app/provider.tsx
  app/read/[id]/page.tsx
  app/sign-up/layout.tsx
  app/sign-up/page.tsx
  app/sign-up/profile/page.tsx
  app/video/info/[_id]/[list]/page.tsx
  app/video/layout.tsx
  app/video/regist/page.tsx
  app/video/update/page.tsx
  package-lock.json
  package.json
  src/components/atom/ThemeButton.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 UI

#7 [UI/6]: Radio atom 추가
  package-lock.json
  package.json
  src/components/atom/Radio.tsx
  tailwind.config.js
Labels: 🎨 UI

#8 [UI/3]: Input atom 구현
  src/components/atom/Input.tsx
Labels: 🎨 UI

#10 [UI/9]: Stepper atom 구현
  src/components/atom/Stepper.tsx
Labels: 🎨 UI

#12 [UI/2] button atom 구현
  src/components/atom/Button.tsx
Labels: 🎨 UI

#15 [UI/13] Plus Button 구현
  package-lock.json
  package.json
  src/components/atom/PlusButton.tsx
Labels: 🎨 UI

#17 [UI/14] Rating Bar atom 구현
  src/components/atom/RatingBar.tsx
  src/components/atom/RatingBarGroup.tsx
Labels: 🎨 UI

#19 [UI/16] SliderButton 구현
  src/components/atom/SliderButton.tsx
Labels: 🎨 UI

#25 [UI/23] ProfileImageUpload atom 구현
  public/basicProfile.svg
  src/components/atom/ProfileImageUploader.tsx
Labels: 🎨 UI

#30 [UI/18] Rating Star atom 구현
  src/components/atom/RatingStar.tsx
  src/components/atom/RatingStarGroup.tsx
Labels: 🎨 UI

#32 [UI/31]: Tooltip atom 구현
  src/components/atom/Tooltip.tsx
Labels: 🎨 UI

#37 [UI/36] Category atom 구현
  src/components/atom/Category.tsx
Labels: 🎨 UI

#44 [Fix/43]: style, class warning error
  app/layout.tsx
Labels: 🐞 BugFix

#46 [Feat/45]: ReactQueryClient 설정
  package-lock.json
  package.json
  src/helper/utils/ReactQueryClient.tsx
Labels: ✨ Feature

#48 [Feat] dev -> main 머지
  app/layout.tsx
  package-lock.json
  package.json
  public/basicProfile.svg
  public/images/_Avatar_.png
  public/images/default.png
  src/components/atom/Avatar.tsx
  src/components/atom/Button.tsx
  src/components/atom/Category.tsx
  src/components/atom/Input.tsx
  src/components/atom/PlusButton.tsx
  src/components/atom/ProfileImageUploader.tsx
  src/components/atom/Radio.tsx
  src/components/atom/Skeleton.tsx
  src/components/atom/SliderButton.tsx
  src/components/atom/Stepper.tsx
  src/components/atom/Tooltip.tsx
  src/components/views/coffeechat/coffeechatList.tsx
  src/helper/utils/ReactQueryClient.tsx
  src/queries/defaultType.ts
  tailwind.config.js
Labels: ✨ Feature

#47 [Feat/40]: 커피챗 리스트 불러오기 및 커피챗 디테일 정보 가져오기 기능 구현
  app/coffeechat/info/[_id]/page.tsx
  app/coffeechat/layout.tsx
  app/coffeechat/page.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/coffeechatList.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/coffeechat/useSelectCoffeechatList.ts
Labels: ✨ Feature, 🎨 UI

#52 [Feat/41] 일반회원/강사회원 회원가입 구현
  app/sign-up/layout.tsx
  app/sign-up/page.tsx
  package-lock.json
  package.json
  src/components/atom/Radio.tsx
  src/components/views/sign-up/SignUp.tsx
  src/components/views/sign-up/SignUpIdPw.tsx
  src/components/views/sign-up/SignUpSellerInfo.tsx
  src/components/views/sign-up/SignUpUserInfo.tsx
  src/components/views/sign-up/consts.ts
  src/components/views/sign-up/types.ts
  src/queries/signUp/useCheckDuplicateEmail.ts
  src/queries/signUp/useCreateUser.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#57 [Feat/54]: 로그인 기능 구현
  app/login/layout.tsx
  app/login/page.tsx
  middleware.ts
  package-lock.json
  package.json
  src/components/views/login/Login.tsx
  src/components/views/sign-up/SignUpSellerInfo.tsx
  src/components/views/sign-up/SignUpUserInfo.tsx
  src/queries/login/useLogin.ts
Labels: ✨ Feature, 📬 API

#53 [Feat/50]: 결제하기 기능 구현
  app/mypage/purchase/page.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/helper/types/order.ts
  src/queries/coffeechat/order/useUpdateOrder.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI

#61 [Feat/59]: 상단바 구현 및 메인페이지 세팅
  app/coffeechat/layout.tsx
  app/layout.tsx
  app/page.tsx
  next.config.js
  package-lock.json
  package.json
  public/images/EduTube.svg
  public/images/main-logo-white.svg
  public/images/menu.svg
  src/components/block/navbar/NavLogin.tsx
  src/components/block/navbar/NavLogout.tsx
  src/components/block/navbar/NavLogoutModal.tsx
  src/components/block/navbar/Navbar.tsx
Labels: ✨ Feature, 🎨 UI

#65 [Feat/58]: 커피챗 페이지 extra 데이터 추가 및 회원 정보 type에 따른 조건부 렌더링 구현
  .env.local
  .gitignore
  src/components/atom/Button.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/coffeechat/order/useUpdateOrder.tsx
  src/queries/member/useSelectMemberInfo.ts
Labels: ✨ Feature, 📬 API, 🎨 UI

#68 [Feat/58] 커피챗 페이지 extra 데이터 추가 및 회원 정보 type에 따른 조건부 렌더링 구현2
  .env.local
  .gitignore
  src/components/atom/Button.tsx
  src/components/views/coffeechat/CoffeechatLists.tsx
  src/components/views/coffeechat/info/CoffeechatInfo.tsx
  src/queries/coffeechat/info/useSelectCoffeechatInfo.tsx
  src/queries/coffeechat/order/useUpdateOrder.tsx
  src/queries/member/useSelectMemberInfo.ts
Labels: ✨ Feature, 📬 API, 🎨 UI
